// Realistic enterprise demo data for HelixOS
// Represents 6 months of operational activity

export const demoDashboardData = {
  userId: 'demo-user-001',
  userName: 'Sarah Chen',
  organization: 'Metro Healthcare Network',
  stats: {
    activeCases: 47,
    pendingTasks: 12,
    totalMembers: 1243,
    totalProviders: 89,
    engagementRate: 87.3,
    outreachSuccess: 91.2,
  },
  recentActivity: [
    { id: '1', type: 'case_closed', description: 'Case #2847 closed: Post-op follow-up completed', timestamp: new Date('2024-01-16T14:30:00'), user: 'Dr. James Wilson' },
    { id: '2', type: 'member_outreach', description: 'Outreach to member James Martinez completed', timestamp: new Date('2024-01-16T13:15:00'), user: 'Sarah Chen' },
    { id: '3', type: 'task_completed', description: '5 tasks completed today', timestamp: new Date('2024-01-16T12:00:00'), user: 'Team' },
    { id: '4', type: 'provider_engagement', description: 'Dr. Sarah Johnson enrolled in new care coordination program', timestamp: new Date('2024-01-15T16:45:00'), user: 'Admin' },
    { id: '5', type: 'case_created', description: 'New case #2856 created: Diabetes management program', timestamp: new Date('2024-01-15T11:20:00'), user: 'Rachel Thompson' },
  ],
  upcomingFollowUps: [
    { id: '1', member: 'Michael Johnson', case: '#2834', dueDate: '2024-01-18', priority: 'high', description: 'Post-surgical follow-up' },
    { id: '2', member: 'Emily Rodriguez', case: '#2847', dueDate: '2024-01-19', priority: 'medium', description: 'Medication adherence check' },
    { id: '3', member: 'David Lee', case: '#2851', dueDate: '2024-01-20', priority: 'high', description: 'Lab results review' },
    { id: '4', member: 'Jennifer Martinez', case: '#2852', dueDate: '2024-01-22', priority: 'medium', description: 'Quarterly assessment' },
  ],
  teamWorkload: [
    { name: 'Sarah Chen', activeCount: 12, completedToday: 8, avatar: 'SC' },
    { name: 'Rachel Thompson', activeCount: 9, completedToday: 6, avatar: 'RT' },
    { name: 'Marcus Johnson', activeCount: 15, completedToday: 11, avatar: 'MJ' },
    { name: 'Lisa Wong', activeCount: 7, completedToday: 5, avatar: 'LW' },
  ],
}

export const demoProviders = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    title: 'MD, Family Medicine',
    specialty: 'Family Medicine',
    organization: 'Metro Health Clinic',
    email: 'sjohnson@metrohealthclinic.com',
    phone: '(555) 123-4567',
    city: 'New York',
    state: 'NY',
    address: '123 Medical Center Dr',
    zipCode: '10001',
    market: 'Northeast',
    status: 'active',
    relatedCases: 42,
    outreachCount: 87,
    lastContact: '2024-01-16',
    performanceRating: 4.8,
    notes: 'Excellent patient outcomes. Highly responsive to care coordination. Strong partnership.',
    specialty_focus: ['Chronic disease management', 'Preventive care', 'Geriatric medicine'],
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    title: 'MD, Cardiology',
    specialty: 'Cardiology',
    organization: 'Cardiac Associates',
    email: 'mchen@cardiacassociates.com',
    phone: '(555) 234-5678',
    city: 'Boston',
    state: 'MA',
    address: '456 Heart Ave',
    zipCode: '02108',
    market: 'Northeast',
    status: 'active',
    relatedCases: 28,
    outreachCount: 52,
    lastContact: '2024-01-15',
    performanceRating: 4.6,
    notes: 'Specializes in complex cardiac cases. Collaborative approach with care teams.',
    specialty_focus: ['Heart disease', 'Arrhythmia management', 'Risk stratification'],
  },
  {
    id: '3',
    name: 'Dr. Jennifer Martinez',
    title: 'MD, Internal Medicine',
    specialty: 'Internal Medicine',
    organization: 'Sunset Medical Group',
    email: 'jmartinez@sunsetmedical.com',
    phone: '(555) 345-6789',
    city: 'Los Angeles',
    state: 'CA',
    address: '789 Wellness Blvd',
    zipCode: '90001',
    market: 'West',
    status: 'active',
    relatedCases: 56,
    outreachCount: 134,
    lastContact: '2024-01-16',
    performanceRating: 4.9,
    notes: 'Top performer. Exceptionally engaged with care coordination initiatives.',
    specialty_focus: ['Diabetes management', 'Hypertension', 'Multi-comorbidity'],
  },
  {
    id: '4',
    name: 'Dr. Robert Williams',
    title: 'MD, Orthopedic Surgery',
    specialty: 'Orthopedics',
    organization: 'Bone & Joint Center',
    email: 'rwilliams@boneandjoint.com',
    phone: '(555) 456-7890',
    city: 'Chicago',
    state: 'IL',
    address: '321 Sports Medicine Ln',
    zipCode: '60601',
    market: 'Midwest',
    status: 'inactive',
    relatedCases: 15,
    outreachCount: 23,
    lastContact: '2023-11-20',
    performanceRating: 4.2,
    notes: 'Limited engagement. May need re-engagement strategy.',
    specialty_focus: ['Joint replacement', 'Sports medicine', 'Trauma'],
  },
  {
    id: '5',
    name: 'Dr. Patricia Lee',
    title: 'MD, Psychiatry',
    specialty: 'Psychiatry',
    organization: 'Mental Health Associates',
    email: 'plee@mentalhealthassoc.com',
    phone: '(555) 567-8901',
    city: 'Seattle',
    state: 'WA',
    address: '654 Mind Care Rd',
    zipCode: '98101',
    market: 'West',
    status: 'active',
    relatedCases: 34,
    outreachCount: 68,
    lastContact: '2024-01-14',
    performanceRating: 4.7,
    notes: 'Great partner for behavioral health integration.',
    specialty_focus: ['Depression', 'Anxiety disorders', 'Medication management'],
  },
]

export const demoMembers = [
  {
    id: '1',
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'mjohnson@email.com',
    phone: '(555) 111-2222',
    dateOfBirth: '1962-03-15',
    memberId: 'MEM-2024-001',
    groupNumber: 'GRP-5847',
    status: 'active',
    enrollmentDate: '2023-06-12',
    riskScore: 'High',
    conditions: ['Diabetes Type 2', 'Hypertension', 'CHF'],
    activeCases: 3,
    lastContact: '2024-01-16',
  },
  {
    id: '2',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'erodriguez@email.com',
    phone: '(555) 222-3333',
    dateOfBirth: '1975-07-22',
    memberId: 'MEM-2024-002',
    groupNumber: 'GRP-5847',
    status: 'active',
    enrollmentDate: '2023-08-01',
    riskScore: 'Medium',
    conditions: ['Asthma', 'Anxiety disorder'],
    activeCases: 2,
    lastContact: '2024-01-15',
  },
  {
    id: '3',
    firstName: 'David',
    lastName: 'Lee',
    email: 'dlee@email.com',
    phone: '(555) 333-4444',
    dateOfBirth: '1958-11-08',
    memberId: 'MEM-2024-003',
    groupNumber: 'GRP-5847',
    status: 'active',
    enrollmentDate: '2023-05-20',
    riskScore: 'High',
    conditions: ['Heart disease', 'Atrial fibrillation', 'Diabetes'],
    activeCases: 4,
    lastContact: '2024-01-16',
  },
  {
    id: '4',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    email: 'jmartinez@email.com',
    phone: '(555) 444-5555',
    dateOfBirth: '1980-01-30',
    memberId: 'MEM-2024-004',
    groupNumber: 'GRP-5847',
    status: 'active',
    enrollmentDate: '2023-09-15',
    riskScore: 'Medium',
    conditions: ['Obesity', 'Pre-diabetes'],
    activeCases: 1,
    lastContact: '2024-01-14',
  },
]

export const demoCases = [
  {
    id: '#2856',
    member: 'Michael Johnson',
    memberId: '1',
    status: 'active',
    caseType: 'Chronic Disease Management',
    provider: 'Dr. Sarah Johnson',
    description: 'Comprehensive diabetes and hypertension management with care coordination',
    createdDate: '2024-01-10',
    assignedTo: 'Sarah Chen',
    outcome: 'In Progress',
    priority: 'High',
    nextStep: 'Lab results review scheduled for 1/18',
  },
  {
    id: '#2851',
    member: 'David Lee',
    memberId: '3',
    status: 'active',
    caseType: 'Cardiac Care Coordination',
    provider: 'Dr. Michael Chen',
    description: 'Post-hospitalization follow-up for heart failure with reduced ejection fraction',
    createdDate: '2024-01-08',
    assignedTo: 'Rachel Thompson',
    outcome: 'In Progress',
    priority: 'High',
    nextStep: 'Cardiology appointment scheduled for 1/22',
  },
  {
    id: '#2852',
    member: 'Jennifer Martinez',
    memberId: '4',
    status: 'active',
    caseType: 'Preventive Care Program',
    provider: 'Dr. Jennifer Martinez',
    description: 'Weight management and lifestyle modification program',
    createdDate: '2024-01-05',
    assignedTo: 'Marcus Johnson',
    outcome: 'In Progress',
    priority: 'Medium',
    nextStep: 'Quarterly assessment scheduled for 1/20',
  },
  {
    id: '#2847',
    member: 'Emily Rodriguez',
    memberId: '2',
    status: 'closed',
    caseType: 'Specialty Care Coordination',
    provider: 'Dr. Patricia Lee',
    description: 'Mental health integration for asthma management',
    createdDate: '2023-12-01',
    assignedTo: 'Sarah Chen',
    outcome: 'Successful',
    priority: 'Medium',
    closedDate: '2024-01-16',
  },
]

export const demoTasks = [
  {
    id: '1',
    title: 'Call Michael Johnson for medication adherence check',
    caseId: '#2856',
    member: 'Michael Johnson',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-01-18',
    assignedTo: 'Sarah Chen',
    description: 'Follow up on blood pressure readings and medication compliance',
  },
  {
    id: '2',
    title: 'Review lab results for David Lee',
    caseId: '#2851',
    member: 'David Lee',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-01-17',
    assignedTo: 'Rachel Thompson',
    description: 'Review troponin levels and BNP from recent blood work',
  },
  {
    id: '3',
    title: 'Schedule follow-up appointment',
    caseId: '#2852',
    member: 'Jennifer Martinez',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-01-15',
    assignedTo: 'Marcus Johnson',
    description: 'Book quarterly assessment appointment',
    completedDate: '2024-01-15',
  },
  {
    id: '4',
    title: 'Email provider summary',
    caseId: '#2856',
    member: 'Michael Johnson',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-01-14',
    assignedTo: 'Sarah Chen',
    description: 'Send care plan summary to Dr. Johnson',
    completedDate: '2024-01-16',
  },
]

export const demoOutreach = [
  {
    id: '1',
    type: 'Phone Call',
    member: 'Michael Johnson',
    date: '2024-01-16',
    notes: 'Discussed medication adherence. Patient reports good compliance.',
    duration: '12 minutes',
    result: 'Positive',
  },
  {
    id: '2',
    type: 'Email',
    member: 'Emily Rodriguez',
    date: '2024-01-15',
    notes: 'Sent care plan and educational materials on asthma management',
    result: 'Delivered',
  },
  {
    id: '3',
    type: 'In-Person Visit',
    member: 'David Lee',
    date: '2024-01-14',
    notes: 'Home visit for vital signs and medication review. All stable.',
    duration: '45 minutes',
    result: 'Positive',
  },
]

export const demoNotes = [
  {
    id: '1',
    caseId: '#2856',
    member: 'Michael Johnson',
    author: 'Sarah Chen',
    date: '2024-01-16',
    content: 'Patient is compliant with medications. Blood pressure readings within target range for past 2 weeks.',
    type: 'Clinical',
  },
  {
    id: '2',
    caseId: '#2851',
    member: 'David Lee',
    author: 'Rachel Thompson',
    date: '2024-01-15',
    content: 'Reviewed latest echocardiogram results with cardiologist. EF improved to 40% from 35% at last visit.',
    type: 'Clinical',
  },
  {
    id: '3',
    caseId: '#2852',
    member: 'Jennifer Martinez',
    author: 'Marcus Johnson',
    date: '2024-01-14',
    content: 'Patient lost 8 lbs in past month. Increased physical activity. Very motivated for program.',
    type: 'Progress',
  },
]

export const demoReports = {
  summary: {
    totalMembers: 1243,
    activeCases: 47,
    completedCases: 156,
    avgEngagementScore: 87.3,
    readmissionRate: 8.2,
    costSavings: '$2.4M',
  },
  trends: [
    { month: 'Jul', cases: 28, outreach: 120, engagement: 82 },
    { month: 'Aug', cases: 32, outreach: 145, engagement: 84 },
    { month: 'Sep', cases: 38, outreach: 168, engagement: 85 },
    { month: 'Oct', cases: 42, outreach: 187, engagement: 86 },
    { month: 'Nov', cases: 45, outreach: 201, engagement: 87 },
    { month: 'Dec', cases: 47, outreach: 219, engagement: 87 },
    { month: 'Jan', cases: 47, outreach: 234, engagement: 87.3 },
  ],
}
