// Comprehensive member seed data with 50+ realistic members
export const memberSeeds = [
  {
    id: 'mem_001',
    name: 'James Rodriguez',
    memberId: 'MEM-2024-001',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 2,
    city: 'New York',
    lastActivity: '2024-01-16',
    email: 'james.rodriguez@email.com',
    phone: '(555) 123-4567',
    dateOfBirth: '1978-05-14',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Metro Health Clinic', 'Cardiac Associates'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-06-01',
  },
  {
    id: 'mem_002',
    name: 'Maria Garcia',
    memberId: 'MEM-2024-002',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'David Chen',
    activeCases: 4,
    city: 'Los Angeles',
    lastActivity: '2024-01-15',
    email: 'maria.garcia@email.com',
    phone: '(555) 234-5678',
    dateOfBirth: '1985-08-22',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Mental Health Support', 'Care Coordination'],
    relatedProviders: ['Sunset Medical Group', 'LA Behavioral Health'],
    activeAuthorizations: 5,
    enrollmentDate: '2023-03-15',
  },
  {
    id: 'mem_003',
    name: 'Robert Thompson',
    memberId: 'MEM-2024-003',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 1,
    city: 'Chicago',
    lastActivity: '2024-01-14',
    email: 'rthompson@email.com',
    phone: '(555) 345-6789',
    dateOfBirth: '1962-03-10',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Medical Records Management'],
    relatedProviders: ['Chicago Medical Center', 'Northwestern Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2022-11-20',
  },
  {
    id: 'mem_004',
    name: 'Angela Davis',
    memberId: 'MEM-2024-004',
    status: 'inactive',
    riskLevel: 'low',
    assignedCaseManager: 'Michael Brown',
    activeCases: 0,
    city: 'Houston',
    lastActivity: '2023-12-01',
    email: 'adavis@email.com',
    phone: '(555) 456-7890',
    dateOfBirth: '1990-11-05',
    preferredCommunication: 'Email',
    activeServices: [],
    relatedProviders: ['Houston Health Partners'],
    activeAuthorizations: 0,
    enrollmentDate: '2023-08-10',
  },
  {
    id: 'mem_005',
    name: 'David Kim',
    memberId: 'MEM-2024-005',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 3,
    city: 'Seattle',
    lastActivity: '2024-01-16',
    email: 'dkim@email.com',
    phone: '(555) 567-8901',
    dateOfBirth: '1975-07-18',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Substance Abuse Support', 'Care Coordination'],
    relatedProviders: ['Seattle Medical Center', 'Evergreen Recovery'],
    activeAuthorizations: 4,
    enrollmentDate: '2023-02-14',
  },
  {
    id: 'mem_006',
    name: 'Patricia Williams',
    memberId: 'MEM-2024-006',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'David Chen',
    activeCases: 1,
    city: 'Boston',
    lastActivity: '2024-01-13',
    email: 'pwilliams@email.com',
    phone: '(555) 678-9012',
    dateOfBirth: '1968-01-25',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management'],
    relatedProviders: ['Boston Medical Center'],
    activeAuthorizations: 1,
    enrollmentDate: '2023-09-01',
  },
  {
    id: 'mem_007',
    name: 'Christopher Lee',
    memberId: 'MEM-2024-007',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 2,
    city: 'Denver',
    lastActivity: '2024-01-12',
    email: 'clee@email.com',
    phone: '(555) 789-0123',
    dateOfBirth: '1988-09-12',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination', 'Medical Records'],
    relatedProviders: ['Denver Health', 'Colorado Wellness Center'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-04-22',
  },
  {
    id: 'mem_008',
    name: 'Linda Johnson',
    memberId: 'MEM-2024-008',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'Michael Brown',
    activeCases: 5,
    city: 'Phoenix',
    lastActivity: '2024-01-16',
    email: 'ljohnson@email.com',
    phone: '(555) 890-1234',
    dateOfBirth: '1972-04-08',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Mental Health', 'Care Coordination', 'Pharmacy'],
    relatedProviders: ['Phoenix Medical Group', 'Arizona Behavioral Health'],
    activeAuthorizations: 6,
    enrollmentDate: '2023-01-10',
  },
  {
    id: 'mem_009',
    name: 'Kevin Martinez',
    memberId: 'MEM-2024-009',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 1,
    city: 'Miami',
    lastActivity: '2024-01-11',
    email: 'kmartinez@email.com',
    phone: '(555) 901-2345',
    dateOfBirth: '1995-12-30',
    preferredCommunication: 'Email',
    activeServices: ['Case Management'],
    relatedProviders: ['Miami Medical Center'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-10-15',
  },
  {
    id: 'mem_010',
    name: 'Susan Anderson',
    memberId: 'MEM-2024-010',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'David Chen',
    activeCases: 3,
    city: 'Philadelphia',
    lastActivity: '2024-01-15',
    email: 'sanderson@email.com',
    phone: '(555) 012-3456',
    dateOfBirth: '1980-06-16',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Philadelphia Medical Group', 'Penn Health'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-07-05',
  },
  // Adding 40 more members for variety
  {
    id: 'mem_011',
    name: 'Thomas White',
    memberId: 'MEM-2024-011',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 2,
    city: 'San Antonio',
    lastActivity: '2024-01-14',
    email: 'twhite@email.com',
    phone: '(555) 123-4568',
    dateOfBirth: '1970-02-28',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Medical Records'],
    relatedProviders: ['San Antonio Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-05-18',
  },
  {
    id: 'mem_012',
    name: 'Elizabeth Brown',
    memberId: 'MEM-2024-012',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'Michael Brown',
    activeCases: 4,
    city: 'San Diego',
    lastActivity: '2024-01-16',
    email: 'ebrown@email.com',
    phone: '(555) 234-5679',
    dateOfBirth: '1981-10-03',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Mental Health', 'Substance Abuse'],
    relatedProviders: ['San Diego Medical', 'Southern California Behavioral'],
    activeAuthorizations: 5,
    enrollmentDate: '2023-03-22',
  },
  {
    id: 'mem_013',
    name: 'Jonathan Black',
    memberId: 'MEM-2024-013',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 2,
    city: 'Dallas',
    lastActivity: '2024-01-13',
    email: 'jblack@email.com',
    phone: '(555) 345-6790',
    dateOfBirth: '1987-07-19',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Dallas Medical Center'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-08-30',
  },
  {
    id: 'mem_014',
    name: 'Catherine Miller',
    memberId: 'MEM-2024-014',
    status: 'inactive',
    riskLevel: 'low',
    assignedCaseManager: 'David Chen',
    activeCases: 0,
    city: 'Austin',
    lastActivity: '2023-11-20',
    email: 'cmiller@email.com',
    phone: '(555) 456-7891',
    dateOfBirth: '1992-05-12',
    preferredCommunication: 'Email',
    activeServices: [],
    relatedProviders: [],
    activeAuthorizations: 0,
    enrollmentDate: '2023-09-01',
  },
  {
    id: 'mem_015',
    name: 'Daniel Wilson',
    memberId: 'MEM-2024-015',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 3,
    city: 'Memphis',
    lastActivity: '2024-01-16',
    email: 'dwilson@email.com',
    phone: '(555) 567-8902',
    dateOfBirth: '1977-11-14',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Substance Abuse', 'Mental Health'],
    relatedProviders: ['Memphis Medical', 'Tennessee Recovery'],
    activeAuthorizations: 4,
    enrollmentDate: '2023-02-08',
  },
  {
    id: 'mem_016',
    name: 'Margaret Taylor',
    memberId: 'MEM-2024-016',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Michael Brown',
    activeCases: 1,
    city: 'Nashville',
    lastActivity: '2024-01-15',
    email: 'mtaylor@email.com',
    phone: '(555) 678-9013',
    dateOfBirth: '1965-08-22',
    preferredCommunication: 'Email',
    activeServices: ['Case Management'],
    relatedProviders: ['Nashville Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-07-10',
  },
  {
    id: 'mem_017',
    name: 'Mark Davis',
    memberId: 'MEM-2024-017',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 2,
    city: 'Baltimore',
    lastActivity: '2024-01-14',
    email: 'mdavis@email.com',
    phone: '(555) 789-0124',
    dateOfBirth: '1989-03-07',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Baltimore Medical Center'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-06-15',
  },
  {
    id: 'mem_018',
    name: 'Nancy Moore',
    memberId: 'MEM-2024-018',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'David Chen',
    activeCases: 4,
    city: 'Milwaukee',
    lastActivity: '2024-01-16',
    email: 'nmoore@email.com',
    phone: '(555) 890-1235',
    dateOfBirth: '1973-09-11',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Mental Health', 'Care Coordination', 'Pharmacy'],
    relatedProviders: ['Milwaukee Medical', 'Wisconsin Wellness'],
    activeAuthorizations: 5,
    enrollmentDate: '2023-01-25',
  },
  {
    id: 'mem_019',
    name: 'Paul Jackson',
    memberId: 'MEM-2024-019',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 1,
    city: 'Albuquerque',
    lastActivity: '2024-01-13',
    email: 'pjackson@email.com',
    phone: '(555) 901-2346',
    dateOfBirth: '1997-01-20',
    preferredCommunication: 'Email',
    activeServices: ['Case Management'],
    relatedProviders: ['Albuquerque Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-11-05',
  },
  {
    id: 'mem_020',
    name: 'Sandra Harris',
    memberId: 'MEM-2024-020',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Michael Brown',
    activeCases: 3,
    city: 'Tucson',
    lastActivity: '2024-01-15',
    email: 'sharris@email.com',
    phone: '(555) 012-3457',
    dateOfBirth: '1984-04-18',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Tucson Medical Center'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-08-20',
  },
  {
    id: 'mem_021',
    name: 'Steven Clark',
    memberId: 'MEM-2024-021',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 1,
    city: 'Louisville',
    lastActivity: '2024-01-14',
    email: 'sclark@email.com',
    phone: '(555) 123-4569',
    dateOfBirth: '1969-12-05',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management'],
    relatedProviders: ['Louisville Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-09-12',
  },
  {
    id: 'mem_022',
    name: 'Carol Robinson',
    memberId: 'MEM-2024-022',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'David Chen',
    activeCases: 4,
    city: 'Portland',
    lastActivity: '2024-01-16',
    email: 'crobinson@email.com',
    phone: '(555) 234-5680',
    dateOfBirth: '1979-06-29',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Mental Health', 'Substance Abuse'],
    relatedProviders: ['Portland Medical Group', 'Pacific Recovery'],
    activeAuthorizations: 5,
    enrollmentDate: '2023-04-18',
  },
  {
    id: 'mem_023',
    name: 'Andrew Martin',
    memberId: 'MEM-2024-023',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 2,
    city: 'Long Beach',
    lastActivity: '2024-01-13',
    email: 'amartin@email.com',
    phone: '(555) 345-6791',
    dateOfBirth: '1986-02-14',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Long Beach Medical'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-07-22',
  },
  {
    id: 'mem_024',
    name: 'Barbara Rodriguez',
    memberId: 'MEM-2024-024',
    status: 'inactive',
    riskLevel: 'low',
    assignedCaseManager: 'Michael Brown',
    activeCases: 0,
    city: 'San Jose',
    lastActivity: '2023-10-15',
    email: 'brodriguez@email.com',
    phone: '(555) 456-7892',
    dateOfBirth: '1991-08-09',
    preferredCommunication: 'Email',
    activeServices: [],
    relatedProviders: [],
    activeAuthorizations: 0,
    enrollmentDate: '2023-08-01',
  },
  {
    id: 'mem_025',
    name: 'Ronald Garcia',
    memberId: 'MEM-2024-025',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 3,
    city: 'Las Vegas',
    lastActivity: '2024-01-16',
    email: 'rgarcia@email.com',
    phone: '(555) 567-8903',
    dateOfBirth: '1974-10-26',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Mental Health', 'Substance Abuse'],
    relatedProviders: ['Las Vegas Medical', 'Nevada Recovery Center'],
    activeAuthorizations: 4,
    enrollmentDate: '2023-03-05',
  },
  {
    id: 'mem_026',
    name: 'Anna Thompson',
    memberId: 'MEM-2024-026',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'David Chen',
    activeCases: 1,
    city: 'Fort Worth',
    lastActivity: '2024-01-15',
    email: 'athompson@email.com',
    phone: '(555) 678-9014',
    dateOfBirth: '1966-05-17',
    preferredCommunication: 'Email',
    activeServices: ['Case Management'],
    relatedProviders: ['Fort Worth Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-10-10',
  },
  {
    id: 'mem_027',
    name: 'Charles Lee',
    memberId: 'MEM-2024-027',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'Jessica Wong',
    activeCases: 2,
    city: 'Columbus',
    lastActivity: '2024-01-14',
    email: 'clee@email.com',
    phone: '(555) 789-0125',
    dateOfBirth: '1988-11-03',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Columbus Medical Center'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-06-28',
  },
  {
    id: 'mem_028',
    name: 'Emily White',
    memberId: 'MEM-2024-028',
    status: 'active',
    riskLevel: 'high',
    assignedCaseManager: 'Michael Brown',
    activeCases: 5,
    city: 'Indianapolis',
    lastActivity: '2024-01-16',
    email: 'ewhite@email.com',
    phone: '(555) 890-1236',
    dateOfBirth: '1980-01-15',
    preferredCommunication: 'Phone',
    activeServices: ['Case Management', 'Mental Health', 'Care Coordination', 'Pharmacy'],
    relatedProviders: ['Indianapolis Medical', 'Indiana Wellness'],
    activeAuthorizations: 6,
    enrollmentDate: '2023-02-14',
  },
  {
    id: 'mem_029',
    name: 'George Harris',
    memberId: 'MEM-2024-029',
    status: 'active',
    riskLevel: 'low',
    assignedCaseManager: 'Sarah Mitchell',
    activeCases: 1,
    city: 'Jacksonville',
    lastActivity: '2024-01-13',
    email: 'gharris@email.com',
    phone: '(555) 901-2347',
    dateOfBirth: '1994-07-21',
    preferredCommunication: 'Email',
    activeServices: ['Case Management'],
    relatedProviders: ['Jacksonville Health'],
    activeAuthorizations: 2,
    enrollmentDate: '2023-11-20',
  },
  {
    id: 'mem_030',
    name: 'Joyce Martin',
    memberId: 'MEM-2024-030',
    status: 'active',
    riskLevel: 'medium',
    assignedCaseManager: 'David Chen',
    activeCases: 2,
    city: 'Austin',
    lastActivity: '2024-01-15',
    email: 'jmartin@email.com',
    phone: '(555) 012-3458',
    dateOfBirth: '1983-09-10',
    preferredCommunication: 'Email',
    activeServices: ['Case Management', 'Care Coordination'],
    relatedProviders: ['Austin Medical'],
    activeAuthorizations: 3,
    enrollmentDate: '2023-08-05',
  },
  // ... Continue pattern for members 31-50
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `mem_${String(i + 31).padStart(3, '0')}`,
    name: ['Frank Smith', 'Grace Jones', 'Henry Clark', 'Iris Lewis', 'Jack Walker', 'Karen Hall', 'Leon Young', 'Mabel King', 'Nathan Wright', 'Olivia Scott', 'Peter Green', 'Quinn Adams', 'Raymond Nelson', 'Stella Carter', 'Theodore Mitchell', 'Ursula Perez', 'Vincent Roberts', 'Wendy Phillips', 'Xavier Campbell', 'Yara Parker'][i],
    memberId: `MEM-2024-${String(i + 31).padStart(3, '0')}`,
    status: i % 8 === 0 ? 'inactive' : 'active',
    riskLevel: ['low', 'medium', 'high'][i % 3],
    assignedCaseManager: ['Sarah Mitchell', 'David Chen', 'Jessica Wong', 'Michael Brown'][i % 4],
    activeCases: [0, 1, 1, 2, 2, 2, 3, 3, 4, 5][i % 10],
    city: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'San Francisco', 'Indianapolis', 'Austin', 'Memphis', 'Boston'][i % 20],
    lastActivity: new Date(2024, 0, Math.max(11, 16 - Math.floor(i / 2))).toISOString().split('T')[0],
    email: `user${i + 31}@email.com`,
    phone: `(555) ${String(i + 31).padStart(3, '0')}-${String(i * 5 % 10000).padStart(4, '0')}`,
    dateOfBirth: `${1960 + (i % 35)}-${String((i % 12) + 1).padStart(2, '0')}-${String((i % 28) + 1).padStart(2, '0')}`,
    preferredCommunication: i % 2 === 0 ? 'Email' : 'Phone',
    activeServices: i % 8 === 0 ? [] : ['Case Management', 'Care Coordination', 'Medical Records', 'Mental Health', 'Substance Abuse'].filter(() => Math.random() > 0.4),
    relatedProviders: i % 8 === 0 ? [] : ['Metro Health', 'Medical Center', 'Health Group', 'Wellness Center'].filter(() => Math.random() > 0.3),
    activeAuthorizations: [0, 1, 1, 2, 2, 2, 3, 3, 4, 5, 6][i % 11],
    enrollmentDate: new Date(2023, Math.floor(i / 3) % 12, Math.max(1, (i % 25) + 1)).toISOString().split('T')[0],
  })),
]

export function getMembers() {
  return memberSeeds
}

export function getMemberById(id: string) {
  return memberSeeds.find(m => m.id === id)
}
