// Comprehensive provider seed data with 35+ realistic providers
export const providerSeeds = [
  {
    id: 'prov_001',
    name: 'Dr. Sarah Johnson',
    specialty: 'Family Medicine',
    organization: 'Metro Health Clinic',
    city: 'New York',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 12,
    primaryContact: 'Dr. Sarah Johnson',
    lastInteraction: '2024-01-16',
    email: 'sjohnson@metrohealthclinic.com',
    phone: '(555) 123-4567',
    serviceAreas: ['New York', 'New Jersey'],
    preferredContact: 'Email',
    partnerships: ['Metro Health Network', 'NYC Care Coalition'],
  },
  {
    id: 'prov_002',
    name: 'Dr. Michael Chen',
    specialty: 'Cardiology',
    organization: 'Cardiac Associates',
    city: 'Boston',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 8,
    primaryContact: 'Dr. Michael Chen',
    lastInteraction: '2024-01-15',
    email: 'mchen@cardiacassociates.com',
    phone: '(555) 234-5678',
    serviceAreas: ['Boston', 'Massachusetts'],
    preferredContact: 'Phone',
    partnerships: ['Boston Medical Center', 'New England Heart Alliance'],
  },
  {
    id: 'prov_003',
    name: 'Dr. Jennifer Martinez',
    specialty: 'Internal Medicine',
    organization: 'Sunset Medical Group',
    city: 'Los Angeles',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 15,
    primaryContact: 'Dr. Jennifer Martinez',
    lastInteraction: '2024-01-14',
    email: 'jmartinez@sunsetmedical.com',
    phone: '(555) 345-6789',
    serviceAreas: ['Los Angeles', 'Southern California'],
    preferredContact: 'Email',
    partnerships: ['LA Care', 'Southern California Medical Network'],
  },
  {
    id: 'prov_004',
    name: 'Dr. David Kumar',
    specialty: 'Orthopedic Surgery',
    organization: 'Advanced Orthopedics Center',
    city: 'Chicago',
    status: 'active',
    performanceScore: 4.6,
    activeCases: 10,
    primaryContact: 'Dr. David Kumar',
    lastInteraction: '2024-01-13',
    email: 'dkumar@advancedortho.com',
    phone: '(555) 456-7890',
    serviceAreas: ['Chicago', 'Illinois', 'Midwest'],
    preferredContact: 'Email',
    partnerships: ['Chicago Health Network', 'Midwest Surgical Alliance'],
  },
  {
    id: 'prov_005',
    name: 'Dr. Amanda Williams',
    specialty: 'Neurology',
    organization: 'Brain & Spine Institute',
    city: 'San Francisco',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 7,
    primaryContact: 'Dr. Amanda Williams',
    lastInteraction: '2024-01-16',
    email: 'awilliams@brainspine.com',
    phone: '(555) 567-8901',
    serviceAreas: ['San Francisco', 'Northern California'],
    preferredContact: 'Phone',
    partnerships: ['UCSF Health', 'Bay Area Neurology Network'],
  },
  {
    id: 'prov_006',
    name: 'Dr. Robert Thompson',
    specialty: 'Pulmonology',
    organization: 'Respiratory Care Specialists',
    city: 'Seattle',
    status: 'active',
    performanceScore: 4.5,
    activeCases: 9,
    primaryContact: 'Dr. Robert Thompson',
    lastInteraction: '2024-01-12',
    email: 'rthompson@respcare.com',
    phone: '(555) 678-9012',
    serviceAreas: ['Seattle', 'Washington'],
    preferredContact: 'Email',
    partnerships: ['Seattle Medical Alliance', 'Pacific Northwest Health'],
  },
  {
    id: 'prov_007',
    name: 'Dr. Lisa Anderson',
    specialty: 'Endocrinology',
    organization: 'Diabetes & Endocrine Center',
    city: 'Denver',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 13,
    primaryContact: 'Dr. Lisa Anderson',
    lastInteraction: '2024-01-16',
    email: 'landerson@endocenter.com',
    phone: '(555) 789-0123',
    serviceAreas: ['Denver', 'Colorado'],
    preferredContact: 'Email',
    partnerships: ['Colorado Health Network', 'Mountain States Diabetes Alliance'],
  },
  {
    id: 'prov_008',
    name: 'Dr. James Wilson',
    specialty: 'Gastroenterology',
    organization: 'GI Specialists Group',
    city: 'Miami',
    status: 'active',
    performanceScore: 4.4,
    activeCases: 11,
    primaryContact: 'Dr. James Wilson',
    lastInteraction: '2024-01-15',
    email: 'jwilson@gispecialists.com',
    phone: '(555) 890-1234',
    serviceAreas: ['Miami', 'Florida'],
    preferredContact: 'Phone',
    partnerships: ['Miami Health Systems', 'Florida Medical Alliance'],
  },
  {
    id: 'prov_009',
    name: 'Dr. Nicole Brown',
    specialty: 'Oncology',
    organization: 'Cancer Treatment Center',
    city: 'Philadelphia',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 6,
    primaryContact: 'Dr. Nicole Brown',
    lastInteraction: '2024-01-14',
    email: 'nbrown@cancercenter.com',
    phone: '(555) 901-2345',
    serviceAreas: ['Philadelphia', 'Pennsylvania'],
    preferredContact: 'Email',
    partnerships: ['Penn Medicine', 'Northeast Cancer Alliance'],
  },
  {
    id: 'prov_010',
    name: 'Dr. Thomas Garcia',
    specialty: 'Psychiatry',
    organization: 'Mental Health Associates',
    city: 'Phoenix',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 14,
    primaryContact: 'Dr. Thomas Garcia',
    lastInteraction: '2024-01-13',
    email: 'tgarcia@mhassociates.com',
    phone: '(555) 012-3456',
    serviceAreas: ['Phoenix', 'Arizona'],
    preferredContact: 'Email',
    partnerships: ['Arizona Mental Health Network', 'Southwest Behavioral Alliance'],
  },
  {
    id: 'prov_011',
    name: 'Dr. Maria Rodriguez',
    specialty: 'Obstetrics & Gynecology',
    organization: 'Women\'s Health Center',
    city: 'Austin',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 9,
    primaryContact: 'Dr. Maria Rodriguez',
    lastInteraction: '2024-01-16',
    email: 'mrodriguez@womenshealth.com',
    phone: '(555) 123-1234',
    serviceAreas: ['Austin', 'Texas'],
    preferredContact: 'Email',
    partnerships: ['UT Health', 'Texas Women\'s Health Alliance'],
  },
  {
    id: 'prov_012',
    name: 'Dr. Christopher Lee',
    specialty: 'Dermatology',
    organization: 'Skin & Beauty Clinic',
    city: 'Los Angeles',
    status: 'active',
    performanceScore: 4.6,
    activeCases: 5,
    primaryContact: 'Dr. Christopher Lee',
    lastInteraction: '2024-01-15',
    email: 'clee@skinbeauty.com',
    phone: '(555) 234-1234',
    serviceAreas: ['Los Angeles', 'Southern California'],
    preferredContact: 'Phone',
    partnerships: ['LA Care', 'California Dermatology Alliance'],
  },
  {
    id: 'prov_013',
    name: 'Dr. Patricia Moore',
    specialty: 'Rheumatology',
    organization: 'Joint & Immune Diseases Center',
    city: 'Boston',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 8,
    primaryContact: 'Dr. Patricia Moore',
    lastInteraction: '2024-01-12',
    email: 'pmoore@jointimmune.com',
    phone: '(555) 345-1234',
    serviceAreas: ['Boston', 'New England'],
    preferredContact: 'Email',
    partnerships: ['Harvard Medical', 'New England Rheumatology Alliance'],
  },
  {
    id: 'prov_014',
    name: 'Dr. Steven Jackson',
    specialty: 'Nephrology',
    organization: 'Kidney Disease Center',
    city: 'New York',
    status: 'active',
    performanceScore: 4.5,
    activeCases: 11,
    primaryContact: 'Dr. Steven Jackson',
    lastInteraction: '2024-01-14',
    email: 'sjackson@kidneycare.com',
    phone: '(555) 456-1234',
    serviceAreas: ['New York', 'New Jersey', 'Connecticut'],
    preferredContact: 'Email',
    partnerships: ['NYU Langone', 'Northeast Kidney Alliance'],
  },
  {
    id: 'prov_015',
    name: 'Dr. Elizabeth White',
    specialty: 'Hepatology',
    organization: 'Liver Disease Institute',
    city: 'San Francisco',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 7,
    primaryContact: 'Dr. Elizabeth White',
    lastInteraction: '2024-01-16',
    email: 'ewhite@livercare.com',
    phone: '(555) 567-1234',
    serviceAreas: ['San Francisco', 'California'],
    preferredContact: 'Phone',
    partnerships: ['UCSF Liver Center', 'West Coast Hepatology Network'],
  },
  {
    id: 'prov_016',
    name: 'Dr. Kevin Mitchell',
    specialty: 'Urology',
    organization: 'Advanced Urology Clinic',
    city: 'Chicago',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 10,
    primaryContact: 'Dr. Kevin Mitchell',
    lastInteraction: '2024-01-13',
    email: 'kmitchell@urologyadvanced.com',
    phone: '(555) 678-1234',
    serviceAreas: ['Chicago', 'Illinois'],
    preferredContact: 'Email',
    partnerships: ['Northwestern Medicine', 'Midwest Urology Alliance'],
  },
  {
    id: 'prov_017',
    name: 'Dr. Rachel Green',
    specialty: 'Infectious Disease',
    organization: 'Infection Control Center',
    city: 'Seattle',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 6,
    primaryContact: 'Dr. Rachel Green',
    lastInteraction: '2024-01-15',
    email: 'rgreen@infectioncenter.com',
    phone: '(555) 789-1234',
    serviceAreas: ['Seattle', 'Washington', 'Oregon'],
    preferredContact: 'Email',
    partnerships: ['UW Medicine', 'Pacific Northwest ID Alliance'],
  },
  {
    id: 'prov_018',
    name: 'Dr. Matthew Davis',
    specialty: 'Hematology',
    organization: 'Blood Disorders Institute',
    city: 'Denver',
    status: 'active',
    performanceScore: 4.6,
    activeCases: 8,
    primaryContact: 'Dr. Matthew Davis',
    lastInteraction: '2024-01-14',
    email: 'mdavis@bloodcare.com',
    phone: '(555) 890-1234',
    serviceAreas: ['Denver', 'Colorado', 'Wyoming'],
    preferredContact: 'Phone',
    partnerships: ['UCHealth', 'Mountain West Hematology Alliance'],
  },
  {
    id: 'prov_019',
    name: 'Dr. Susan Taylor',
    specialty: 'Ophthalmology',
    organization: 'Vision Care Specialists',
    city: 'Miami',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 9,
    primaryContact: 'Dr. Susan Taylor',
    lastInteraction: '2024-01-16',
    email: 'staylor@visioncare.com',
    phone: '(555) 901-1234',
    serviceAreas: ['Miami', 'Florida'],
    preferredContact: 'Email',
    partnerships: ['Bascom Palmer', 'Florida Vision Alliance'],
  },
  {
    id: 'prov_020',
    name: 'Dr. Daniel Harris',
    specialty: 'Otolaryngology',
    organization: 'ENT Surgical Center',
    city: 'Philadelphia',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 7,
    primaryContact: 'Dr. Daniel Harris',
    lastInteraction: '2024-01-12',
    email: 'dharris@entsurgical.com',
    phone: '(555) 012-1234',
    serviceAreas: ['Philadelphia', 'Pennsylvania'],
    preferredContact: 'Email',
    partnerships: ['Penn ENT', 'Northeast ENT Alliance'],
  },
  {
    id: 'prov_021',
    name: 'Dr. Jessica Clark',
    specialty: 'Pediatrics',
    organization: 'Children\'s Health Center',
    city: 'Phoenix',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 16,
    primaryContact: 'Dr. Jessica Clark',
    lastInteraction: '2024-01-15',
    email: 'jclark@childrenshealth.com',
    phone: '(555) 123-5678',
    serviceAreas: ['Phoenix', 'Arizona'],
    preferredContact: 'Email',
    partnerships: ['Phoenix Children\'s Hospital', 'Southwest Pediatric Alliance'],
  },
  {
    id: 'prov_022',
    name: 'Dr. Andrew Scott',
    specialty: 'Geriatrics',
    organization: 'Senior Care Specialists',
    city: 'Austin',
    status: 'active',
    performanceScore: 4.5,
    activeCases: 12,
    primaryContact: 'Dr. Andrew Scott',
    lastInteraction: '2024-01-14',
    email: 'ascott@seniorcare.com',
    phone: '(555) 234-5678',
    serviceAreas: ['Austin', 'Texas'],
    preferredContact: 'Phone',
    partnerships: ['Dell Medical School', 'Texas Geriatric Alliance'],
  },
  {
    id: 'prov_023',
    name: 'Dr. Margaret Lee',
    specialty: 'Sports Medicine',
    organization: 'Athletic Performance Center',
    city: 'Los Angeles',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 10,
    primaryContact: 'Dr. Margaret Lee',
    lastInteraction: '2024-01-16',
    email: 'mlee@athleticperformance.com',
    phone: '(555) 345-5678',
    serviceAreas: ['Los Angeles', 'Southern California'],
    preferredContact: 'Email',
    partnerships: ['LA Sports Medicine', 'California Athletes Alliance'],
  },
  {
    id: 'prov_024',
    name: 'Dr. Jonathan Black',
    specialty: 'Emergency Medicine',
    organization: 'Emergency Care Network',
    city: 'Boston',
    status: 'active',
    performanceScore: 4.6,
    activeCases: 20,
    primaryContact: 'Dr. Jonathan Black',
    lastInteraction: '2024-01-13',
    email: 'jblack@emergencycare.com',
    phone: '(555) 456-5678',
    serviceAreas: ['Boston', 'Massachusetts'],
    preferredContact: 'Phone',
    partnerships: ['Mass General', 'Boston Emergency Medicine Alliance'],
  },
  {
    id: 'prov_025',
    name: 'Dr. Catherine Hall',
    specialty: 'Anesthesiology',
    organization: 'Anesthesia Specialists',
    city: 'San Francisco',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 8,
    primaryContact: 'Dr. Catherine Hall',
    lastInteraction: '2024-01-15',
    email: 'chall@anesthesia.com',
    phone: '(555) 567-5678',
    serviceAreas: ['San Francisco', 'California'],
    preferredContact: 'Email',
    partnerships: ['UCSF Anesthesia', 'Bay Area Surgery Alliance'],
  },
  {
    id: 'prov_026',
    name: 'Dr. Edward Mitchell',
    specialty: 'Pathology',
    organization: 'Clinical Pathology Lab',
    city: 'Chicago',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 4,
    primaryContact: 'Dr. Edward Mitchell',
    lastInteraction: '2024-01-14',
    email: 'emitchell@pathologylab.com',
    phone: '(555) 678-5678',
    serviceAreas: ['Chicago', 'Illinois', 'Midwest'],
    preferredContact: 'Email',
    partnerships: ['Northwestern Lab Services', 'Midwest Pathology Alliance'],
  },
  {
    id: 'prov_027',
    name: 'Dr. Helen Martinez',
    specialty: 'Radiology',
    organization: 'Imaging Diagnostics Center',
    city: 'Seattle',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 5,
    primaryContact: 'Dr. Helen Martinez',
    lastInteraction: '2024-01-16',
    email: 'hmartinez@imagingdiag.com',
    phone: '(555) 789-5678',
    serviceAreas: ['Seattle', 'Washington'],
    preferredContact: 'Phone',
    partnerships: ['UW Radiology', 'Pacific Northwest Imaging Alliance'],
  },
  {
    id: 'prov_028',
    name: 'Dr. Frank Thompson',
    specialty: 'Physical Medicine & Rehabilitation',
    organization: 'Rehab & Recovery Center',
    city: 'Denver',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 11,
    primaryContact: 'Dr. Frank Thompson',
    lastInteraction: '2024-01-13',
    email: 'fthompson@rehab.com',
    phone: '(555) 890-5678',
    serviceAreas: ['Denver', 'Colorado'],
    preferredContact: 'Email',
    partnerships: ['UCHealth Rehab', 'Colorado Recovery Alliance'],
  },
  {
    id: 'prov_029',
    name: 'Dr. Victoria Brown',
    specialty: 'Immunology',
    organization: 'Immune Disorders Center',
    city: 'Miami',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 6,
    primaryContact: 'Dr. Victoria Brown',
    lastInteraction: '2024-01-15',
    email: 'vbrown@immunecenter.com',
    phone: '(555) 901-5678',
    serviceAreas: ['Miami', 'Florida'],
    preferredContact: 'Email',
    partnerships: ['Miami Medical Center', 'Florida Immunology Alliance'],
  },
  {
    id: 'prov_030',
    name: 'Dr. Richard White',
    specialty: 'Genetics',
    organization: 'Genetic Counseling Center',
    city: 'Philadelphia',
    status: 'active',
    performanceScore: 4.6,
    activeCases: 5,
    primaryContact: 'Dr. Richard White',
    lastInteraction: '2024-01-14',
    email: 'rwhite@genetics.com',
    phone: '(555) 012-5678',
    serviceAreas: ['Philadelphia', 'Pennsylvania'],
    preferredContact: 'Phone',
    partnerships: ['Penn Genetics', 'Northeast Genetic Alliance'],
  },
  {
    id: 'prov_031',
    name: 'Dr. Michelle Johnson',
    specialty: 'Palliative Care',
    organization: 'Comfort & Palliative Care',
    city: 'Phoenix',
    status: 'active',
    performanceScore: 4.8,
    activeCases: 9,
    primaryContact: 'Dr. Michelle Johnson',
    lastInteraction: '2024-01-16',
    email: 'mjohnson@palliativecare.com',
    phone: '(555) 123-9999',
    serviceAreas: ['Phoenix', 'Arizona'],
    preferredContact: 'Email',
    partnerships: ['Phoenix Hospice', 'Arizona Palliative Alliance'],
  },
  {
    id: 'prov_032',
    name: 'Dr. Brian Anderson',
    specialty: 'Sleep Medicine',
    organization: 'Sleep Disorders Lab',
    city: 'Austin',
    status: 'active',
    performanceScore: 4.7,
    activeCases: 7,
    primaryContact: 'Dr. Brian Anderson',
    lastInteraction: '2024-01-13',
    email: 'banderson@sleeplab.com',
    phone: '(555) 234-9999',
    serviceAreas: ['Austin', 'Texas'],
    preferredContact: 'Email',
    partnerships: ['UT Sleep Center', 'Texas Sleep Medicine Alliance'],
  },
  {
    id: 'prov_033',
    name: 'Dr. Angela Wilson',
    specialty: 'Occupational Medicine',
    organization: 'Workplace Health Services',
    city: 'Los Angeles',
    status: 'inactive',
    performanceScore: 4.4,
    activeCases: 2,
    primaryContact: 'Dr. Angela Wilson',
    lastInteraction: '2024-01-05',
    email: 'awilson@workplacehealth.com',
    phone: '(555) 345-9999',
    serviceAreas: ['Los Angeles', 'Southern California'],
    preferredContact: 'Email',
    partnerships: ['CalOSHA', 'California Workplace Alliance'],
  },
  {
    id: 'prov_034',
    name: 'Dr. George Lopez',
    specialty: 'Travel Medicine',
    organization: 'International Health Center',
    city: 'Boston',
    status: 'active',
    performanceScore: 4.6,
    activeCases: 6,
    primaryContact: 'Dr. George Lopez',
    lastInteraction: '2024-01-16',
    email: 'glopez@travelhealth.com',
    phone: '(555) 456-9999',
    serviceAreas: ['Boston', 'New England'],
    preferredContact: 'Phone',
    partnerships: ['Boston Travel Clinic', 'Northeast Travel Medicine Alliance'],
  },
  {
    id: 'prov_035',
    name: 'Dr. Laura Martinez',
    specialty: 'Preventive Medicine',
    organization: 'Wellness & Prevention Institute',
    city: 'San Francisco',
    status: 'active',
    performanceScore: 4.9,
    activeCases: 8,
    primaryContact: 'Dr. Laura Martinez',
    lastInteraction: '2024-01-15',
    email: 'lmartinez@wellness.com',
    phone: '(555) 567-9999',
    serviceAreas: ['San Francisco', 'California'],
    preferredContact: 'Email',
    partnerships: ['UCSF Wellness', 'California Prevention Alliance'],
  },
]

export const getProviders = () => providerSeeds

export const getProviderById = (id: string) =>
  providerSeeds.find(p => p.id === id)
